services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - library-mysql
    env_file:
      - .env

  library-mysql:
    image: mysql:8
    container_name: library-mysql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
