@resource = auth

### Đăng nhập
POST {{base_url}}/{{resource}}/login
Content-Type: application/json
x-api-key: {{api_key}}

{
    "username": "admin",
    "password": "anhemiit@123"
}

###

### Làm mới token
POST {{base_url}}/{{resource}}/token/refresh
Content-Type: application/json
x-api-key: {{api_key}}

{
    "refreshToken": "{{refresh_token}}"
}
