@resource = permissions

### Lấy danh sách quyền
GET {{base_url}}/{{resource}}
x-api-key: {{api_key}}
Authorization: Bearer {{access_token}}

###

### Lấy chi tiết quyền

@id = NEW_TEST_PERMISSION_01
GET {{base_url}}/{{resource}}/{{id}}
x-api-key: {{api_key}}
Authorization: Bearer {{access_token}}

### Tạo quyền mới
POST {{base_url}}/{{resource}}
Content-Type: application/json
x-api-key: {{api_key}}
Authorization: Bearer {{access_token}}

{
    "id": "NEW_TEST_PERMISSION_01",
    "name": "New Test Permission 01",
    "description": "New Test Permission 01 Description"
}

###
